import os

MAX_SENTENCES_TO_FETCH = 5
CONTENT_PATH = './content'
CONTENT_IMAGES_PATH = CONTENT_PATH + '/images'
CONTENT_SOUND_PATH = CONTENT_PATH + '/music'
CONTENT_DEFAULT_PATH = CONTENT_PATH + '/default'